RealEstate_Dapper_UI/Controllers/BottomGridController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RealEstate_Dapper_UI.Dtos.BottomGridDtos;
using RealEstate_Dapper_UI.Dtos.ServiceDtos;
using RealEstate_Dapper_UI.StaticValues;
using System.Text;

namespace RealEstate_Dapper_UI.Controllers
{
    public class BottomGridController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public BottomGridController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync(PublicValues.Url + "BottomGrids");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultBottomGridDto>>(jsonData);
                return View(values);
            }
            return View();
        }
        [HttpGet]
        public IActionResult CreateBottomGrid()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateBottomGrid(CreateBottomGridDto createBottomGridDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createBottomGridDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync(PublicValues.Url + "BottomGrids", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> DeleteBottomGrid(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responsMessage = await client.DeleteAsync(PublicValues.Url + $"BottomGrids/{id}");
            if (responsMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> UpdateBottomGrid(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync(PublicValues.Url + $"BottomGrids/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonDate = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<UpdateBottomGridDto>(jsonDate);
                return View(values);
            }
            return View();
        }
        public async Task<IActionResult> UpdateBottomGrid(UpdateBottomGridDto updateBottomGridDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(updateBottomGridDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync(PublicValues.Url + "BottomGrids", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

RealEstate_Dapper_UI/Views/BottomGrid/CreateBottomGrid.cshtml
@model CreateBottomGridDto
@{
    ViewData["Title"] = "CreateBottomGrid";
    Layout = "~/Views/Admin/Index.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Yeni Hizmet Ekleme Sayfası</h6>
                <div class="table-responsive">
                    <form asp-action="CreateBottomGrid" asp-controller="BottomGrid" method="post">
                        <label>Hizmet Adı</label>
                        <input type="text" asp-for="Title" class="form-control" />
                        <br />
                        <label>İkon</label>
                        <input type="text" asp-for="Icon" class="form-control" />
                        <br />
                        <label>Açıklama</label>
                        <input type="text" asp-for="Description" class="form-control" />
                        <br />
                        <button class="btn btn-primary" type="submit">Veriyi Kaydet</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

RealEstate_Dapper_UI/Views/BottomGrid/Index.cshtml
@model List<ResultBottomGridDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/Index.cshtml";
    int count = 0;
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Öne Çıkan Alanlar Listesi</h6>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Hizmet Başlığı</th>
                                <th scope="col">Sil</th>
                                <th scope="col">Güncelle</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th scope="row">@item.BottomGridId</th>
                                    <td>@item.Title</td>
                                    <td><a href="/BottomGrid/DeleteBottomGrid/@item.BottomGridId" class="btn btn-sm btn-outline-danger">Sil</a></td>
                                    <td><a href="/BottomGrid/UpdateBottomGrid/@item.BottomGridId" class="btn btn-sm btn-outline-success">Güncelle</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a href="/BottomGrid/CreateBottomGrid/" class="btn btn-sm btn-outline-info">Yeni Öne Çıkan İlan Girişi</a>
                </div>
            </div>
        </div>
    </div>
</div>

RealEstate_Dapper_UI/Views/BottomGrid/UpdateBottomGrid.cshtml
@model UpdateBottomGridDto
@{
    ViewData["Title"] = "UpdateBottomGrid";
    Layout = "~/Views/Admin/Index.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Yeni Hizmet Ekleme Sayfası</h6>
                <div class="table-responsive">
                    <form asp-action="UpdateBottomGrid" asp-controller="BottomGrid" method="post">
                        <input type="hidden" asp-for="BottomGridId"/>
                        <label>Hizmet Adı</label>
                        <input type="text" asp-for="Title" class="form-control" />
                        <br />
                        <label>İkon</label>
                        <input type="text" asp-for="Icon" class="form-control" />
                        <br />
                        <label>Açıklama</label>
                        <input type="text" asp-for="Description" class="form-control" />
                        <br />
                        <button class="btn btn-primary" type="submit">Veriyi Kaydet</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>